services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
