FROM node:22-alpine

WORKDIR /usr/src/app

COPY --chown=node:node package.json yarn.lock .

RUN yarn install --frozen-lockfile

COPY --chown=node:node . .

ENV NODE_ENV production

USER node

CMD [ "yarn", "migration:run" ]
